version: '3.9'

services:
  insttantt.fieldsmanagement.api:
    image: ${DOCKER_REGISTRY-}insttanttfieldsmanagementapi
    build:
      context: .
      dockerfile: Insttantt.FieldsManagement.Api/Dockerfile
    ports:
          - "81:81"
    depends_on:
        - "mongo"
  mongo:
     image: mongo
     ports:
         - "27017:27017"
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
     SA_PASSWORD: Coldplay18
     ACCEPT_EULA: Y
    ports:
        - "1433:1433"